[[graph]]
name = "test_graph_0"

[[graph.vertex]]
op = "opr1"
start = true

[[graph.vertex]]
op = "opr2"
deps = ["opr1"]
next = ["opr4"]

[[graph.vertex]]
op = "opr3"
deps = ["opr1"]
next = ["opr4"]

[[graph.vertex]]
op = "opr4"
next = ["cond1"]

[[graph.vertex]]
id = "cond1"
cond = "opr3 > opr2"
next_on_ok = ["opr5"]
next_on_fail = ["opr6"]

[[graph.vertex]]
op = "opr5"

[[graph.vertex]]
op = "opr6"



[[graph]]
name = "test_graph_1"

[[graph.vertex]]
op = "opr1"
start = true
output = [{name = "opr1_out", id="m1"}]

[[graph.vertex]]
op = "opr2"
input = [{name = "opr1_out", id="m1"}]
output = [{name = "opr2_out", id="m2"}]

[[graph.vertex]]
op = "opr3"
input = [{name = "opr1_out", id="m1"}]
output = [{name = "opr3_out", id="m3"}]

[[graph.vertex]]
op = "opr4"
input = [{name = "opr2_out", id="m2"}, {name = "opr3_out", id="m3"}]

[[graph.vertex]]
id = "cond1"
cond = "opr3 > opr2"
deps = ["opr4"]
next_on_ok = ["opr5"]
next_on_fail = ["opr6"]

[[graph.vertex]]
op = "opr5"

[[graph.vertex]]
op = "opr6"